image: node:9

services:
  - docker:dind

stages:
  - publish

variables:
  DOCKER_DRIVER: overlay

after_script:
  - rm * -r
  - rm -rf .[^.] .??*
  - ls -l

publish:
  stage: publish
  script:
    - npm install
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish --access=public